set.seed(1)
x = 1:5
y = rnorm(5, sd = 0.5)
setnicepar()
plot(x, y, panel.first=grid(), type="n", xlab=NA, ylab=NA)
m = lm(y ~ x)
abline(m, lty = 2, lwd=2)
pred = predict(m, data.frame(x))
segments(1:5, y, 1:5, pred, col=c("steelblue", "firebrick"), lwd=2)
points(x, y,  pch=21, bg = "black")
text(1.6, 0.1, "observed")
text(3.3, -0.2, "residual", col="steelblue")
text(4.3,  0.6, "residual", col="firebrick")
text(3.2, 0.2, "Line of best fit")